export const GAME = {
  tickRate: 30,
  snapshotRate: 20,
  interpolationDelayMs: 90,
  minimumInterpolationDelayMs: 75,
  maximumInterpolationDelayMs: 160,
  maximumExtrapolationMs: 55,
  gridSize: 236,
  cellSize: 16,
  arenaRadius: 1824,
  playerSpeed: 172,
  maximumTurnRate: 4.6,
  playerRadius: 14,
  trailWidth: 22,
  trailPointSpacing: 8,
  maximumTrailPoints: 700,
  startingTerritoryCells: 81,
  spawnTerritoryBuffer: 64,
  botTarget: 12,
  botThinkIntervalMs: 170,
  respawnDelayMs: 1800,
  spawnMovementDelayMs: 1000,
  spawnProtectionMs: 1300,
  movementRateLimit: 45,
  leaderboardSize: 5
} as const;

export const BOT_NAMES = [
  'Atlas',
  'Inkwell',
  'Patch',
  'Canvas',
  'Doodle',
  'Mosaic',
  'Vector',
  'Saffron',
  'Indigo',
  'Stencil',
  'Pixel',
  'Contour'
] as const;
